# Generated by Django 4.1.7 on 2023-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
