# Generated by Django 4.1.7 on 2023-03-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
