# Generated by Django 4.1.7 on 2023-03-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
